services:
  echocron:
    build: .
    container_name: echocron
    env_file:
      - .env
    extra_hosts:
      - "${PI_NAME}:${PI_IP}"
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ./output:/output
    environment:
      - TZ=America/New_York
    restart: unless-stopped
